package com.duker.mygift.model;

/**
 * Menu generated by MyEclipse Persistence Tools
 */

public class Menu implements java.io.Serializable {

	// Fields

	/**
	 * 菜单id
	 */
	private String menuId;

	/**
	 * 菜单名称
	 */
	private String menuName;

	/**
	 * 菜单类型
	 */
	private Integer menuType;

	/**
	 * 菜单排序值,值越大越靠前
	 */
	private Long menuIndex;

	/**
	 * 父菜单id
	 */
	private String parentId;

	/**
	 * url地址
	 */
	private String url;

	/**
	 * 地址打开目标值
	 */
	private String target;

	/**
	 * 父菜单
	 */
	private Menu parentMenu;

	/**
	 * 权限组
	 */
	private RightGroup right;

	// Constructors

	/** default constructor */
	public Menu() {
	}

	/** minimal constructor */
	public Menu(String menuName) {
		this.menuName = menuName;
	}

	/** full constructor */
	public Menu(String menuName, Integer menuType, Long menuIndex,
			String parentId, String url, String target, RightGroup right) {
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuIndex = menuIndex;
		this.parentId = parentId;
		this.url = url;
		this.target = target;
		this.right = right;
	}

	// Property accessors

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	public Long getMenuIndex() {
		return this.menuIndex;
	}

	public void setMenuIndex(Long menuIndex) {
		this.menuIndex = menuIndex;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public RightGroup getRight() {
		return right;
	}

	public void setRight(RightGroup right) {
		this.right = right;
	}

	public Menu getParentMenu() {
		return parentMenu;
	}

	public void setParentMenu(Menu parentMenu) {
		this.parentMenu = parentMenu;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		Menu m1 = getParentMenu();
		StringBuilder name = new StringBuilder(getMenuName());
		while (m1 != null) {
			name.insert(0, "-->");
			name.insert(0, m1.getMenuName());
			m1 = m1.getParentMenu();
		}

		return name.toString();
	}
}