package com.duker.mygift.model;

import java.util.HashSet;
import java.util.Set;

/**
 * RightGroup generated by MyEclipse Persistence Tools
 */

public class RightGroup implements java.io.Serializable {

	// Fields

	/**
	 * 权限组id
	 */
	private String rightId;

	/**
	 * 权限组名称
	 */
	private String rightName;

	/**
	 * 拥有权限的角色
	 */
	private Set<Role> roles = new HashSet<Role>(0);

	/**
	 * url列表
	 */
	private Set<String> urls = new HashSet<String>(0);

	// Constructors

	/** default constructor */
	public RightGroup() {
	}

	/** minimal constructor */
	public RightGroup(String rightName) {
		this.rightName = rightName;
	}

	/** full constructor */
	public RightGroup(String rightName, Set<Role> roles, Set<String> urls) {
		this.rightName = rightName;
		this.roles = roles;
		this.urls = urls;
	}

	// Property accessors

	public String getRightId() {
		return rightId;
	}

	public void setRightId(String rightId) {
		this.rightId = rightId;
	}

	public String getRightName() {
		return rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<String> getUrls() {
		return urls;
	}

	public void setUrls(Set<String> urls) {
		this.urls = urls;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((rightId == null) ? 0 : rightId.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof RightGroup))
			return false;
		RightGroup other = (RightGroup) obj;
		if (rightId == null) {
			if (other.rightId != null)
				return false;
		}
		else if (!rightId.equals(other.rightId))
			return false;
		return true;
	}

}