package com.duker.mygift.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by MyEclipse Persistence Tools
 */

public class Role implements java.io.Serializable {

	// Fields

	/**
	 * 角色id
	 */
	private String roleId;

	/**
	 * 角色名称
	 */
	private String roleName;

	/**
	 * 父角色id
	 */
	private String parentRoleId;

	/**
	 * 角色描述
	 */
	private String description;

	/**
	 * 父角色
	 */
	private Role parentRole;

	/**
	 * 子角色
	 */
	private Set<Role> childrenRoles = new HashSet<Role>(0);

	/**
	 * 角色所拥有的权限组
	 */
	private Set<RightGroup> rights = new HashSet<RightGroup>(0);

	/**
	 * 用户列表
	 */
	private Set<UserInfo> users = new HashSet<UserInfo>(0);

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleId, String parentRoleId) {
		this.roleId = roleId;
		this.parentRoleId = parentRoleId;
	}

	/** full constructor */
	public Role(String roleName, String parentRoleId, String description,
			Role parentRole, Set<RightGroup> rights, Set<UserInfo> users) {
		this.roleName = roleName;
		this.parentRoleId = parentRoleId;
		this.description = description;
		this.parentRole = parentRole;
		this.rights = rights;
		this.users = users;
	}

	// Property accessors

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getParentRoleId() {
		return parentRoleId;
	}

	public void setParentRoleId(String parentRoleId) {
		this.parentRoleId = parentRoleId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Role getParentRole() {
		return parentRole;
	}

	public void setParentRole(Role parentRole) {
		this.parentRole = parentRole;
	}

	public Set<Role> getChildrenRoles() {
		return childrenRoles;
	}

	public void setChildrenRoles(Set<Role> childrenRoles) {
		this.childrenRoles = childrenRoles;
	}

	public Set<RightGroup> getRights() {
		return rights;
	}

	public void setRights(Set<RightGroup> rights) {
		this.rights = rights;
	}

	public Set<UserInfo> getUsers() {
		return users;
	}

	public void setUsers(Set<UserInfo> users) {
		this.users = users;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result
				+ ((roleName == null) ? 0 : roleName.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Role))
			return false;
		Role other = (Role) obj;
		if (roleName == null) {
			if (other.roleName != null)
				return false;
		}
		else if (!roleName.equals(other.roleName))
			return false;
		return true;
	}

}